# Generated by Django 3.2.5 on 2021-07-11 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='department',
        ),
        migrations.RemoveField(
            model_name='patientdischargedetails',
            name='OtherCharge',
        ),
        migrations.RemoveField(
            model_name='patientdischargedetails',
            name='doctorFee',
        ),
        migrations.RemoveField(
            model_name='patientdischargedetails',
            name='medicineCost',
        ),
        migrations.RemoveField(
            model_name='patientdischargedetails',
            name='roomCharge',
        ),
        migrations.RemoveField(
            model_name='patientdischargedetails',
            name='total',
        ),
    ]
