# Generated by Django 3.2.5 on 2021-07-16 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_auto_20210711_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='assignedDoctorId',
        ),
    ]
